version: 2
updates:
- package-ecosystem: pip
  directory: "/src"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - edelbluth
  assignees:
  - edelbluth
